name: Build Static Next.js Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build and export static site
        run: |
          npm run build
          npm run export  # Creates 'out' folder with static files

      - name: List generated files
        run: |
          echo "Generated static files:"
          find out -type f -name "*.html" | head -10
          echo "Total files: $(find out -type f | wc -l)"
          echo "Total size: $(du -sh out/)"

      - name: Upload static site
        uses: actions/upload-artifact@v3
        with:
          name: static-website
          path: out/
          retention-days: 30

      # Optional: Check for broken links
      - name: Test built site
        run: |
          npm install -g serve
          serve -s out -p 3000 &
          sleep 5
          curl -f http://localhost:3000 || echo "Homepage check failed"
